module: jenkins
version: v1
runtime: custom
vm: true
api_version: 1
threadsafe: on

manual_scaling:
  instances: 1

resources:
  cpu: 4
  disk_size_gb: 200
  memory_gb: 8

beta_settings:
  # Add more service account scopes here to give Jenkins more power.
  service_account_scopes: https://www.googleapis.com/auth/projecthosting,https://www.googleapis.com/auth/gerritcodereview,https://www.googleapis.com/auth/devstorage.full_control
  # Necessary to allow Jenkins to run Docker inside of Docker.
  run_docker_privileged: true

builtins:
- appstats: on

handlers:

# Favicon.  Without this, the browser hits this once per page view.
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

# Main app.  All the real work is here.
- url: /.*
  script: main.application
  # Restrict Jenkins access to only developers of the project.
  login: admin
